#!/usr/bin/env python3
"""
Build `data/gallery-manifest.js` for the Hooke Wilding Webapp.

Why:
  Browsers can't reliably list directories on a static site, so the Gallery page
  uses a small JS manifest of image paths that we generate from the repo.

Rules:
  - Include images under `assets/` (png/jpg/jpeg/webp/gif/svg)
  - Exclude anything under `assets/field-guide/` (internet-sourced)
  - Ignore dotfiles (e.g. .DS_Store)

Usage:
  python3 tools/build_gallery_manifest.py
"""

from __future__ import annotations

import datetime as _dt
import os
from pathlib import Path


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def categorize(src: str) -> tuple[str, str]:
    # returns (category, label)
    base = src.split("/")[-1]

    if src.startswith("assets/about/"):
        return ("About", base)
    if src == "assets/hooke-farm-watercolour.png":
        return ("Artwork", "Hooke Farm watercolor map")
    if src == "assets/sunflower.webp":
        return ("Artwork", "Sunflower")
    if src.startswith("assets/hookewildingmisc/"):
        return ("Hooke wilding misc", os.path.splitext(base)[0])

    if src.startswith("assets/features/"):
        if base == "thumb.png" or base.startswith("page-"):
            return ("Info boards", base)
        return ("Feature photos", os.path.splitext(base)[0])

    return ("Other", os.path.splitext(base)[0])


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    assets_dir = repo_root / "assets"
    out_file = repo_root / "data" / "gallery-manifest.js"

    imgs: list[str] = []
    for p in assets_dir.rglob("*"):
        if not p.is_file():
            continue
        if p.name.startswith("."):
            continue
        if p.suffix.lower() not in IMAGE_EXTS:
            continue
        rel = rel_posix(p, repo_root)
        if rel.startswith("assets/field-guide/"):
            continue
        imgs.append(rel)

    imgs = sorted(set(imgs))

    # Stable ordering (requested): About, Hooke wilding misc, Feature photos, Info boards, Artwork, Other
    order = {
        "About": 1,
        "Hooke wilding misc": 2,
        "Feature photos": 3,
        "Info boards": 4,
        "Artwork": 5,
        "Other": 6,
    }

    entries = []
    for src in imgs:
        category, label = categorize(src)
        entries.append({"src": src, "category": category, "label": label})

    entries.sort(key=lambda e: (order.get(e["category"], 99), e["category"], e["src"]))

    ts = _dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

    out_lines: list[str] = []
    out_lines.append("// Auto-generated by tools/build_gallery_manifest.py")
    out_lines.append("// Gallery images for Hooke Farm Wilding Portal (excluding assets/field-guide).")
    out_lines.append("window.__HOOKE_GALLERY__ = {")
    out_lines.append(f'  generatedAt: "{ts}",')
    out_lines.append("  images: [")
    for e in entries:
        out_lines.append(
            f'    {{ src: "{e["src"]}", category: "{e["category"]}", label: "{e["label"]}" }},'
        )
    out_lines.append("  ],")
    out_lines.append("};")
    out_lines.append("")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {out_file} ({len(entries)} images)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


