#!/usr/bin/env python3
"""
Build `data/gallery-manifest.js` for the Hooke Wilding Webapp.

Why:
  Browsers can't reliably list directories on a static site, so the Gallery page
  uses a small JS manifest of image paths that we generate from the repo.

Rules:
  - Include images under `assets/` (png/jpg/jpeg/webp/gif/svg)
  - Exclude anything under `assets/field-guide/` (internet-sourced)
  - Ignore dotfiles (e.g. .DS_Store)

Usage:
  python3 tools/build_gallery_manifest.py
"""

from __future__ import annotations

import datetime as _dt
import os
from pathlib import Path
import json


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"}


def rel_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _load_feature_titles(repo_root: Path) -> dict[str, str]:
    """
    Best-effort lookup from feature id -> feature title (for gallery tags).
    """
    src = repo_root / "data" / "features.json"
    try:
        data = json.loads(src.read_text(encoding="utf-8"))
    except OSError:
        return {}
    except json.JSONDecodeError:
        return {}

    out: dict[str, str] = {}
    features = data.get("features")
    if not isinstance(features, list):
        return {}
    for f in features:
        if not isinstance(f, dict):
            continue
        fid = f.get("id")
        title = f.get("title")
        if isinstance(fid, str) and fid.strip() and isinstance(title, str) and title.strip():
            out[fid.strip()] = title.strip()
    return out


def categorize(src: str, feature_titles: dict[str, str]) -> tuple[str, str, list[str]]:
    # returns (category, label, tags)
    base = src.split("/")[-1]

    if src.startswith("assets/before/"):
        return ("Before", os.path.splitext(base)[0], ["Before"])
    if src.startswith("assets/about/"):
        return ("About", base, ["About"])
    if src == "assets/hooke-farm-watercolour.png":
        return ("Artwork", "Hooke Farm watercolor map", ["Artwork"])
    if src == "assets/sunflower.webp":
        return ("Artwork", "Sunflower", ["Artwork"])
    if src.startswith("assets/hookewildingmisc/"):
        return ("Misc", os.path.splitext(base)[0], ["Misc"])

    if src.startswith("assets/features/"):
        # assets/features/<featureId>/<file>
        parts = src.split("/")
        fid = parts[2] if len(parts) >= 3 else ""
        title = feature_titles.get(fid, fid) if fid else ""
        if base == "thumb.png" or base.startswith("page-"):
            tags = ["Info board"]
            if title:
                tags.append(title)
            return ("Info boards", base, tags)
        tags = ["Feature photo"]
        if title:
            tags.append(title)
        return ("Feature photos", os.path.splitext(base)[0], tags)

    return ("Other", os.path.splitext(base)[0], ["Other"])


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    assets_dir = repo_root / "assets"
    out_file = repo_root / "data" / "gallery-manifest.js"
    feature_titles = _load_feature_titles(repo_root)

    imgs: list[str] = []
    for p in assets_dir.rglob("*"):
        if not p.is_file():
            continue
        if p.name.startswith("."):
            continue
        if p.suffix.lower() not in IMAGE_EXTS:
            continue
        rel = rel_posix(p, repo_root)
        if rel.startswith("assets/field-guide/"):
            continue
        imgs.append(rel)

    imgs = sorted(set(imgs))

    # Stable ordering (requested): Before, About, Misc, Feature photos, Info boards, Artwork, Other
    order = {
        "Before": 1,
        "About": 2,
        "Misc": 3,
        "Feature photos": 4,
        "Info boards": 5,
        "Artwork": 6,
        "Other": 7,
    }

    entries = []
    for src in imgs:
        category, label, tags = categorize(src, feature_titles)
        try:
            # There's no reliable "created" time cross-platform; use mtime as a sensible proxy.
            st = (repo_root / src).stat()
            mtime = int(st.st_mtime)
        except OSError:
            mtime = 0
        created_iso = _dt.datetime.utcfromtimestamp(mtime).replace(microsecond=0).isoformat() + "Z" if mtime else ""
        entries.append(
            {
                "src": src,
                "category": category,
                "label": label,
                "tags": tags,
                "createdMs": mtime * 1000,
                "createdAt": created_iso,
            }
        )

    entries.sort(key=lambda e: (order.get(e["category"], 99), e["category"], e["src"]))

    ts = _dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

    out_lines: list[str] = []
    out_lines.append("// Auto-generated by tools/build_gallery_manifest.py")
    out_lines.append("// Gallery images for Hooke Farm Wilding Portal (excluding assets/field-guide).")
    out_lines.append("window.__HOOKE_GALLERY__ = {")
    out_lines.append(f'  generatedAt: "{ts}",')
    out_lines.append("  images: [")
    for e in entries:
        tags_js = json.dumps(e["tags"], ensure_ascii=False)
        out_lines.append(
            f'    {{ src: "{e["src"]}", category: "{e["category"]}", label: "{e["label"]}", tags: {tags_js}, createdMs: {int(e["createdMs"])}, createdAt: "{e["createdAt"]}" }},'
        )
    out_lines.append("  ],")
    out_lines.append("};")
    out_lines.append("")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {out_file} ({len(entries)} images)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


